name: Run Django server

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Start Django server
      run: python manage.py runserver

